name: Trigger Website Build

on:
  push:
    branches:
      - main

jobs:
  trigger-website-action:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Website Build
        run: |
          curl -XPOST -u "cumany:${{secrets.ACCESS_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/ma5d/ma5d.github.io/dispatches \
          --data '{"event_type": "update_docs"}'