name: Trigger Website Build

on:
  push:
    branches:
      - main

jobs:
  trigger-website-action:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Website Build
        run: |
           curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           -H "Content-Type: application/json" \
           https://api.github.com/repos/ma5d/ma5d.github.io/dispatches \
           -d '{"event_type":"jvm","client_payload":{"unit":false,"integration":true}}'